DROP TABLE IF EXISTS ongoing;
DROP TABLE IF EXISTS history;

CREATE TABLE ongoing (
  id INT AUTO_INCREMENT PRIMARY KEY ,
  fileName TEXT NOT NULL,
  url LONGTEXT NOT NULL,
  fileSize LONG NOT NULL,
  schTime DATETIME NOT NULL,
  location LONGTEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE history (
  id INT AUTO_INCREMENT PRIMARY KEY ,
  fileName TEXT NOT NULL,
  url LONGTEXT NOT NULL,
  fileSize LONG NOT NULL,
  schTime DATETIME NOT NULL,
  location LONGTEXT NOT NULL,
  finishedTime DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

